# Klompen

Klompen is a static blog generation engine, with an ever growing tower
of dependencies.

## Dependencies
   - **HTML::Tiny** *HTML Generation*
   - **JSON** *State saving, configuration*
   - **File::Path** *Folder creation*
   - **File::Slurp** *Reading in and writing out files*
   - **Text::Markdown** *Obvious, really :)*
   - **XML::RSS::SimpleGen** *Generating RSS feeds*

## Arguments

Only one, optional: Path to an alternate configuration file.

## Configuration

Configuration is per-blog, with the settings pulled from klompen.cfg
by default, or any named config file; a mostly self-explanatory JSON
file with the following:

### Options

* `site_name`
   Name of the site.
* `base_url`
   URL the blog will be hosted at. (That is, if the blog will be in
   the folder blog/ at example.com; this should be
   http://example.com/blog/"
* `includes`
   Directory to look in for include files.

### posts

This section contains the following:

#### Output

* `extension`
  Extension to give the output files. (The output generated by Klompen
  will be static HTML, but you may want to include PHP code in the
  header or footer; this is where you would change the extension to
  .php)
* `directory`
   Directory to output to. This may be relative or absolute. All other
   output will be relative to this.
* `encoding`
   Encoding that the output textfiles will be in.

##### `urls`

* `stylesheet`
   Link to the stylesheet you want to use.
* `tags`
  Path, relative to the output directory, you want the tag/category
  files to be placed.
* `archives`
  Relative path to the location that posts will be output to.
* `rss`
   Name of file where the RSS feed is generated.
* `author_info`
  Location where author profile pages will be stored.

#### `input`

 *** Currently, there is no option to allow you to relocate the author
  profile/info page source directory; I'll add this soon. ***

* `extension`
  File extension to use to find source posts when scanning
  the source dir (This can be blank if your source posts
  don't have a file extension on them.)
* `directory`
   Folder to scan for source posts in.
* `encoding`
  Character encoding to expect input files in.

### links

This part of the config is an array of links, which will be added to
the 'links' section of the output page's sidebar. See the example
config.

## Using

To use Klompen, one writes one's posts in the source directory; in
plain-text (UTF-8, preferably), using the header to provide
information such as the post's title, date of publication, the list of
tags/categories (comma separated) and the post's ID (This line will be
automatically added, if it is not manually inserted. However, one can
control the post's ID by setting it manually, which may be useful to
some users. (i.e. Those transferring a blog from Wordpress, so you can
put your posts at the same post IDs as they were under WP))

Please see the article template (doc/article_template) for the header.

Then, when one wants to publish/update one's posts; run ./klompen
(After modifying the configuration to point to your posts' source
directory, and the directory you wish to output to, of course.)  and
every post in the source directory will be converted into a HTML page
in the output directory.
